## Tensorflow Basics

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

In [3]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
x = tf.constant(value=4, dtype=tf.float32, shape=(1,1), name='x')
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [5]:
# Rank 1 tensor
x = tf.constant([1,2,3,4])
print(x)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [6]:
# rank 2 tensor
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [8]:
# rank 3 tensor
x = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print(x)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [11]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [12]:
x = tf.ones((3,3), dtype=tf.int32)
print(x)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)


In [13]:
x = tf.zeros((3,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [14]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [15]:
# random from the uniform distribution
x = tf.random.uniform((3,3))
print(x)

tf.Tensor(
[[0.16749012 0.10866714 0.44833636]
 [0.2433765  0.71042657 0.9133725 ]
 [0.5968534  0.26653624 0.6918858 ]], shape=(3, 3), dtype=float32)


In [16]:
# random values drawn from normal distribution
x = tf.random.normal((3,3))
print(x)

tf.Tensor(
[[-0.90637803 -0.4562799   1.4442176 ]
 [-1.0233043  -0.7963415  -0.15551387]
 [-0.3523402  -0.2969026   1.0918733 ]], shape=(3, 3), dtype=float32)


In [17]:
x = tf.range(10)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [18]:
# above if we look, x is int32, lets cast to float32
x = tf.cast(x, dtype=tf.float32)
print(x)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)


In [23]:
# Operations are all elementwise
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])
z1 = tf.add(x,y)
z2 = x + y
print(z1)
print(z2)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [24]:
z1 = tf.subtract(x,y)
z2 = x - y
print(z1)
print(z2)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [25]:
z1 = tf.multiply(x,y)
z2 = x * y
print(z1)
print(z2)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [26]:
z1 = tf.divide(x,y)
z2 = x / y
print(z1)
print(z2)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)
